### ISSUE TITLE
Client Pulls CraftableExtraLives from the Server, but Uses the Client Side Recipe

### ISSUE THREAD

**Issue by Yuogusy** [hamstar0/tml-lives-mod#1]
I'm not 100% sure I understand why it is doing this by looking at your code (i'm not the best coder), but I am running a dedicated server with the Lives mod, and the clients seem to respect the server setting for both Enabled and CraftableExtraLives, however changing the server's recipe for ExtraLifeGoldCoins or ExtraLifeVoodoo doesn't have any effect. Each client uses it's local recipe. I have two clients to test with, both with different settings client side for these, and each one shows and uses their own recipe.  This means non-moderators on my server can simply set "ExtraLifeGoldCoins": 1 and "ExtraLifeVoodoo": false on their end and get as many 1-Ups as they want right from the start.

Also, I hesitate to say this without re-testing, but when my players initially joined, it seemed like their client also ignored InitialLives as well, yet I swore it did get MaxLives form the server. I ended up just giving them the difference in 1-Ups. Not sure when I can re-test that as all my players have already lost some lives and are not at max.

Luckily no has realized this yet or is deep enough to get a voodoo doll, so I just set CraftableExtraLives to false for the time being and will just sell them their 1-Ups manually if they get that far.

Thanks much for the otherwise great mod!

**Comment by hamstar0** [comment]
Thanks for reporting these. This sounds like more of the usual load order weirdness I've been battling with for ages in many mods. I'll try to address these.

**Comment by hamstar0** [comment]
Tell me if Lives v2.0.1 addresses any of these issues.
